name: ibnt
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  flutter_bloc: ^8.1.5
  flutter_modular: ^6.3.3
  firebase_core: ^2.27.0
  image_picker: ^1.0.8
  google_sign_in: ^6.2.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  uuid: ^3.0.7
  uno: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^1.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: Karma
      fonts:
        - asset: assets/Karma-Bold.ttf
        - asset: assets/Karma-Light.ttf
        - asset: assets/Karma-Medium.ttf
        - asset: assets/Karma-Regular.ttf
        - asset: assets/Karma-SemiBold.ttf

  assets:
    - assets/images/logo_image.jpg
