// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_lpBdhJ4KdqMzASreTEGcagfIMEwzV9U',
    appId: '1:683866552:android:8b1867f7bfe62904bab74d',
    messagingSenderId: '683866552',
    projectId: 'ibnt-316a7',
    storageBucket: 'ibnt-316a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgoOUTpgCDiI5krlLwfS9_-K9yChBfnnk',
    appId: '1:683866552:ios:09e471e09fc16f4abab74d',
    messagingSenderId: '683866552',
    projectId: 'ibnt-316a7',
    storageBucket: 'ibnt-316a7.appspot.com',
    androidClientId: '683866552-7prj47oc9bvu3bk10j98jdv6lp0mnstb.apps.googleusercontent.com',
    iosClientId: '683866552-q580g4dod1rfgfe1iikf77goul6d0khr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibnt',
  );
}
